### ISSUE TITLE
sbt reactive app does not respect proxies

### ISSUE THREAD

**Issue by erip** [lightbend/sbt-reactive-app#100]
I'm not sure if this is a bug in sbt-reactive-app or one of its dependencies (like sbt-native-packager), but I'm running into this problem most directly using sbt-reactive-app, so I'll report it here for now.

When issuing `sbt "deploy minikube"`, build contexts are sent to the docker daemon. It seems that proxy information is disregarded in this send. I'll post the relevant bits of the stacktrace below:

```
$ sbt -debug "deploy minikube"
[residual] arg = 'deploy minikube'
[residual] arg = 'deploy minikube'
[process_args] java_version = '1.8'
# Executing command line:
java
-Dhttp.proxyHost=proxy.acme.com
-Dhttp.nonProxyHosts='...'
-Dhttps.proxyHost=proxy.acme.com
-Dhttps.proxyPort=80
-Dhttps.nonProxyHosts='...'
-Xmx4096M
-Xss2M
-XX:MaxMetaspaceSize=2048m
-jar
/usr/local/Cellar/sbt/1.0.4/libexec/bin/sbt-launch.jar
"deploy minikube"

...

[info] Done packaging.
[error] Error: failed to download "lightbend-helm-charts/reactive-sandbox"
09:39:07.392 [pool-8-thread-3] DEBUG com.lightbend.lagom.internal.api.tools.ServiceDetector - Loading service discovery class: ProjectOneLoader
[info] Packaging /Users/erip/projectOne/target/scala-2.11/projectOne_2.11-0.0.1-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Packaging/Users/erip/projectOne/target/scala-2.11/projectOne_2.11-0.0.1-SNAPSHOT-sources.jar ...
[info] Wrote /Users/erip/projectOne/target/scala-2.11/projectOne_2.11-0.0.1-SNAPSHOT-sources.pom
[info] Done packaging.
[info] Sending build context to Docker daemon  146.8MB
[info] Step 1/35 : FROM openjdk:8-jre-alpine
[error] Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

```

However, if I try to create a stupid Dockerfile with only this `FROM`, it successfully builds...

```
~/repro ⌚ 10:02:36
$ cat Dockerfile
FROM openjdk:8-jre-alpine

~/repro ⌚ 10:02:37
$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM openjdk:8-jre-alpine
 ---> b1bd879ca9b3
Successfully built b1bd879ca9b3
Successfully tagged test:latest

~/repro ⌚ 10:02:40
$ docker images | grep test
test                latest              b1bd879ca9b3        2 months ago        82MB
```

I'm not sure if this is a bug, a quirk, or user error... but I couldn't find any documentation leading me to a definitive conclusion.

**Comment by longshorej** [comment]
Hrm - yeah, I don't think we've done much (if any) testing for proxies TBH.

What's unclear to me is whether your second example, invoking `docker` directly, is using a proxy or not. Can you confirm that `HTTPS_PROXY` et al was set for that?

**Comment by erip** [comment]
On my Mac:

```
$ [[ ! -z $HTTPS_PROXY ]] && echo $?
0
$ docker info | grep -i proxy
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
```

And running the Alpine container

```
$ docker run --rm -it openjdk:8-jre-alpine
/ # [[ ! -z $HTTPS_PROXY ]] && echo $?
0
```

**Comment by erip** [comment]
It seems like as a part of `"deploy minikube"`, there's an error when publishing... locally? Maybe this is relevant?

```
[info] Step 1/33 : FROM openjdk:8-jre-alpine
[error] Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority
[error] java.lang.RuntimeException: Nonzero exit value: 1
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:335)
[error] 	at com.lightbend.rp.sbtreactiveapp.BasicApp$.$anonfun$projectSettings$46(App.scala:344)
[error] 	at com.lightbend.rp.sbtreactiveapp.BasicApp$.$anonfun$projectSettings$46$adapted(App.scala:231)
```

**Comment by erip** [comment]
The proxy was not (directly) a proxy problem at all. minikube creates user-issued certs in `.minikube` which aren't trusted in my corporate proxy's HTTPS rewriting mechanism.
