### ISSUE TITLE
Missing project version results in cryptic error

### ISSUE THREAD

**Issue by longmuir** [lightbend/sbt-reactive-app#105]
If, for whatever reason, you omit a version in your build.sbt, `sbt docker:publishLocal` will result in the following error, which will be difficult for most people to diagnose:
```
Jamies-MacBook-Pro:akka-samples-cluster-scala jamielongmuir$ sbt docker:publishLocal
[info] Loading global plugins from /Users/jamielongmuir/.sbt/0.13/plugins
[info] Loading project definition from /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/project
[info] Set current project to akka-sample-cluster-scala (in build file:/Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/)
[info] Updating {file:/Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/}akka-sample-cluster-scala...
[info] Wrote /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/target/scala-2.12/akka-sample-cluster-scala_2.12-HEAD+20180529-1601.pom
[info] Resolving jline#jline;2.14.3 ...
[info] Done updating.
[info] Packaging /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/target/scala-2.12/akka-sample-cluster-scala_2.12-HEAD+20180529-1601-sources.jar ...
[info] Main Scala API documentation to /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/target/scala-2.12/api...
[info] Done packaging.
[info] Compiling 1 Scala source to /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/target/scala-2.12/classes...
model contains 7 documentable templates
[info] Packaging /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/target/scala-2.12/akka-sample-cluster-scala_2.12-HEAD+20180529-1601.jar ...
[info] Done packaging.
[info] Main Scala API documentation successful.
[info] Packaging /Users/jamielongmuir/code/lightbend-examples/akka-samples-cluster-scala/target/scala-2.12/akka-sample-cluster-scala_2.12-HEAD+20180529-1601-javadoc.jar ...
[info] Done packaging.
[error] invalid argument "akka-sample-cluster-scala:HEAD+20180529-1601" for "-t, --tag" flag: invalid reference format
[error] See 'docker build --help'.
java.lang.RuntimeException: Nonzero exit value: 125
	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:341)
	at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$23.apply(DockerPlugin.scala:123)
	at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$projectSettings$23.apply(DockerPlugin.scala:121)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (docker:publishLocal) Nonzero exit value: 125
[error] Total time: 5 s, completed 29-May-2018 4:01:43 PM
```
Ideally, it'd be nice to have a meaningful error message, though I have a feeling this may involve SBT Native Packager. At a minimum, ensuring a version is defined should be a documented step for configuring the SBT reactive app plugin.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).

**Comment by pierregangloff** [comment]
OMG THANK YOU @longmuir for writting up this question (I google this error "Nonzero exit value: 125" and found this thread). Indeed the error was cryptic but your comment describing that it was caused by a missing version in the build.sbt fixed it for me as well. I created a StackOverflow question for it and self-answered it in case it helps anyone else. Thanks!!
