### ISSUE TITLE
sbt deploy minikube fails with minikube start -vm-provider=none for docker

### ISSUE THREAD

**Issue by carwilki** [lightbend/sbt-reactive-app#107]
```
[error] /mnt/sda1/projects/hades/services/scanner-impl/target/minikube-exec: line 5: none: command not found
[error] java.lang.RuntimeException: Nonzero exit value: 127
[error]         at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:335)
[error]         at com.lightbend.rp.sbtreactiveapp.BasicApp$.$anonfun$projectSettings$46(App.scala:344)
[error]         at com.lightbend.rp.sbtreactiveapp.BasicApp$.$anonfun$projectSettings$46$adapted(App.scala:231)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

Generated minikube-exec 
```
#!/usr/bin/env bash

set -e

eval $(minikube docker-env)

exec "$@"
```
```
$ minikube docker-env
```
'none' driver does not support 'minikube docker-env' command

can this be made to not generate and execute if the host is running docker? Looking at the code there doesn't seem to be an option that will skip or test to see if this will work.

Running ubuntu 18.04

Thanks!

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
