### ISSUE TITLE
chown: /rp-start: Operation not permitted

### ISSUE THREAD

**Issue by cunei** [lightbend/sbt-reactive-app#117]
Somewhat related to #111. Using v1.2.2, I get:
```
[info] chown: /rp-start: Operation not permitted
[info] Removing intermediate container 6d19f5096a43
[error] The command 'chown -R daemon:daemon /rp-start' returned a non-zero code: 1
```
Ubuntu 16.04, Docker 1.3.1

**Comment by alanngai** [comment]
@cunei does this block any other planned task or is it an enhancement we can prioritize for later?

**Comment by cunei** [comment]
I just used a previous version, so nothing is blocked on my side.

**Comment by alanngai** [comment]
do you mean a previous version of rp?  How big of a problem do you think this would be to our users?

**Comment by cunei** [comment]
Yes, I used v1.1.0 of sbt-reactive-app in place of v1.2.x during testing. It seems a rather significant issue, actually.
To reproduce, just change in https://github.com/fsat/hello-reactive-tooling the plugin version to 1.2.1 or 1.2.2, then run `deploy minikube`. The error prevents the creation of the docker image.
```
[info] Removing intermediate container 2d1f85b254f4
[error] The command 'chown -R daemon:daemon /rp-start' returned a non-zero code: 1
[error] java.lang.RuntimeException: Nonzero exit value: 1
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:341)
[error] 	at com.lightbend.rp.sbtreactiveapp.BasicApp$.$anonfun$projectSettings$46(App.scala:345)
[...]
```

**Comment by ihostage** [comment]
Docker commands for Docker >= 17.09
```
[info] * Cmd(FROM,WrappedArray(openjdk:8-jre-alpine))
[info] * Cmd(RUN,Vector(/sbin/apk, add, --no-cache, bash))
[info] * Cmd(RUN,WrappedArray(id -g daemon || addgroup daemon))
[info] * Cmd(RUN,WrappedArray(id -u daemon || adduser daemon daemon))
[info] * Cmd(WORKDIR,WrappedArray(/opt/docker))
[info] * Cmd(ADD,WrappedArray(--chown=daemon:daemon opt /opt))
[info] * Cmd(USER,WrappedArray(daemon))
[info] * ExecCmd(ENTRYPOINT,Vector())
[info] * ExecCmd(CMD,List())
[info] * Cmd(COPY,WrappedArray(--chown=daemon:daemon, rp-start, /rp-start))
```

Docker commands for Docker < 17.09
```
[info] * Cmd(FROM,WrappedArray(openjdk:8-jre-alpine))
[info] * Cmd(RUN,Vector(/sbin/apk, add, --no-cache, bash))
[info] * Cmd(RUN,WrappedArray(id -g daemon || addgroup daemon))
[info] * Cmd(RUN,WrappedArray(id -u daemon || adduser daemon daemon))
[info] * Cmd(WORKDIR,WrappedArray(/opt/docker))
[info] * Cmd(ADD,WrappedArray(opt /opt))
[info] * ExecCmd(RUN,List(chown, -R, daemon:daemon, .))
[info] * Cmd(USER,WrappedArray(daemon))
[info] * ExecCmd(ENTRYPOINT,Vector())
[info] * ExecCmd(CMD,List())
[info] * Cmd(COPY,WrappedArray(rp-start, /rp-start))
[info] * ExecCmd(RUN,Vector(chown, -R, daemon:daemon, /rp-start))
```

`chown` not permitted, because it after `USER daemon` command.

I think that problem in this place. 
https://github.com/lightbend/sbt-reactive-app/blob/08d5e397db83f30307d4dd1564b58580912eeaa9/src/main/scala/com/lightbend/rp/sbtreactiveapp/App.scala#L528-L536
